field: b5eb01ec-a6ed-4a08-9438-64e7138b08f0 # FAQs
fieldLayouts:
  529896ec-dad3-4d01-8366-e2c4f7b33144:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: e0264ea5-7834-42de-9f8f-c611149453d0 # Question
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 53b49b35-e7bc-4e11-95fb-038ec716cf25
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2bb6f342-1735-446e-b9fe-754f94dac82f # Answer
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ea93a09f-e0e0-4dcb-8d31-f466b6e1c60a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 98dbc824-8c89-4138-9b0f-011a96875a7a # Links
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2d0d1694-aec7-4e93-beac-26460e8770c2
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 3719d24a-d689-4ef9-b20a-252e6b3a6984
        userCondition: null
fields:
  2bb6f342-1735-446e-b9fe-754f94dac82f: # Answer
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: answer
    instructions: null
    name: Answer
    searchable: true
    settings:
      errorMessage: 'Unable to find component class ''craft\redactor\Field''.'
      expectedType: craft\redactor\Field
      settings:
        __assoc__:
          -
            - availableTransforms
            - '*'
          -
            - availableVolumes
            - '*'
          -
            - cleanupHtml
            - true
          -
            - columnType
            - text
          -
            - purifierConfig
            - ''
          -
            - purifyHtml
            - '1'
          -
            - redactorConfig
            - Standard.json
          -
            - removeEmptyTags
            - '1'
          -
            - removeInlineStyles
            - '1'
          -
            - removeNbsp
            - '1'
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\MissingField
  98dbc824-8c89-4138-9b0f-011a96875a7a: # Links
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: links
    instructions: null
    name: Links
    searchable: true
    settings:
      addRowLabel: 'Add a row'
      columnType: text
      columns:
        __assoc__:
          -
            - col1
            -
              __assoc__:
                -
                  - heading
                  - 'Link Text'
                -
                  - handle
                  - linkText
                -
                  - width
                  - ''
                -
                  - type
                  - singleline
          -
            - col2
            -
              __assoc__:
                -
                  - heading
                  - 'Link Url'
                -
                  - handle
                  - linkUrl
                -
                  - width
                  - ''
                -
                  - type
                  - singleline
      maxRows: null
      minRows: null
      staticRows: false
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Table
  e0264ea5-7834-42de-9f8f-c611149453d0: # Question
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: question
    instructions: null
    name: Question
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: faqs
name: FAQs
sortOrder: 1
