columnSuffix: null
contentColumnType: string
fieldGroup: bfbd2913-36d8-4e54-9f9c-644e793f0ae9 # Episodes
handle: episodeHosts
instructions: null
name: 'Episode Hosts'
searchable: true
settings:
  allowSelfRelations: false
  branchLimit: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  selectionLabel: null
  showSiteMenu: true
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Users
