columnSuffix: null
contentColumnType: string
fieldGroup: bfbd2913-36d8-4e54-9f9c-644e793f0ae9 # Episodes
handle: episodeTranscript
instructions: 'CSV format transcript of the episode, with tabs as the field delimeter'
name: 'Episode Transcript'
searchable: false
settings:
  allowSelfRelations: false
  allowSubfolders: false
  allowUploads: true
  allowedKinds:
    - text
  branchLimit: null
  defaultUploadLocationSource: 'volume:e69c8edb-d562-4367-9a05-91a6fd2c7d99' # Devmode Episodes
  defaultUploadLocationSubpath: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: 1
  minRelations: null
  previewMode: full
  restrictFiles: true
  restrictLocation: false
  restrictedDefaultUploadSubpath: null
  restrictedLocationSource: 'volume:e69c8edb-d562-4367-9a05-91a6fd2c7d99' # Devmode Episodes
  restrictedLocationSubpath: null
  selectionLabel: 'Choose a CSV Transcript'
  showSiteMenu: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  sources:
    - 'volume:bd8ef0d7-f73b-4138-ac52-c14d11dd780e' # Devmode Transcripts
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
