columnSuffix: null
contentColumnType: text
fieldGroup: 88db3e41-57f4-404d-b3ea-762b09c37afe # Errors
handle: errorHeadline
instructions: null
name: 'Error Headline'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: text
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
