columnSuffix: null
contentColumnType: string
fieldGroup: 49649e9a-033b-4ddf-9f3d-26a480502993 # About
handle: faqs
instructions: null
name: FAQs
searchable: true
settings:
  contentTable: '{{%matrixcontent_faqs}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
