columnSuffix: null
contentColumnType: string(255)
fieldGroup: 12aa936c-807f-4ec3-81dc-69283a344171 # Profile
handle: profileTwitterUrl
instructions: null
name: 'Profile Twitter URL'
searchable: true
settings:
  maxLength: 255
  types:
    - url
translationKeyFormat: null
translationMethod: none
type: craft\fields\Url
