columnSuffix: null
contentColumnType: string
fieldGroup: 0c790066-43c5-4b67-b6d9-8492fa40cf71 # Show
handle: showEmail
instructions: null
name: 'Show Email'
searchable: true
settings:
  placeholder: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Email
