fieldLayouts:
  871fe128-2837-48cb-a9ac-29f46ae27488:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: d57f6696-fe10-4cb3-936d-4619d794c531
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 90f85740-1500-4535-94f5-e7e3507dbf38
        userCondition: null
handle: episodesIndex
hasTitleField: false
name: 'Episodes Index'
section: 1a66bf43-6fcc-4a78-bf36-0f350b930430 # Episodes Index
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: ''
