fieldLayouts:
  92845533-f123-4a66-937a-1f9ed6ddea24:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: Title
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 3d750002-d8ff-4378-969d-d9d495cf730c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 324e7a11-3346-41e7-a29d-4636ab907e51 # Episode Number
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 782aff15-4a67-4411-b942-34a9813e9d3d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8011817c-9518-4a31-9aa8-cad6d4a08b81 # Episode Summary
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7d8fa7d9-965c-4779-91a8-31e868723435
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 61953a92-8b34-4678-9bae-fd5a45142f26 # Episode Tags
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fcd8e7c2-5887-4c9b-a14f-33824c06ae4e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a5cf9c0d-1797-4a60-8c47-bc28c5f01a95 # Episode Hosts
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5bec380a-f7bf-4f4f-a3e5-448a71799b05
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7e338b73-ac10-44cf-892e-04afc0164991 # Episode Guests
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 98473791-ca92-4006-b401-18dcc5e40f52
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0090f7a3-1e22-4fb5-9ae0-01de38805601 # Episode Media
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 95bb9703-944f-4733-981a-64d6e0407439
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 523395ea-5738-4ca5-a119-f32221ea5ca8 # Episode Transcript
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9b41cd8f-189b-468b-bfd3-b6cdc1f5e91a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 07f04bdf-277d-4010-9fbe-497cd9593324 # Related Episodes
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3a287ead-92eb-48f3-b889-0f01456729b7
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8c9dd611-b43b-4e22-b076-3f6a6362c93e # Episode Reference Links
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 05b9d534-5e33-4039-a373-7029bd40969f
            userCondition: null
            warning: null
            width: 100
        name: Episodes
        uid: 5eafa0ab-9127-4b8e-8e6c-c3d07be2fbae
        userCondition: null
handle: episodes
hasTitleField: true
name: Episodes
section: c1f6af30-7375-4feb-92ef-a3ed16ba69b2 # Episodes
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: ''
